plugins {
    // Java
    id 'java'

    // Spring Boot
    // https://start.spring.io/
    // https://plugins.gradle.org/plugin/org.springframework.boot
    // https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'

    // Asciidoctor (for Spring REST Docs)
    // https://plugins.gradle.org/plugin/org.asciidoctor.jvm.convert
    id "org.asciidoctor.jvm.convert" version "4.0.4"
}

group = 'com.markruler'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    asciidoctorExt
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // H2 Database (in-memory database)
//    testRuntimeOnly 'com.h2database:h2'
    runtimeOnly 'com.h2database:h2'

    // REST Docs
    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
}

ext {
    // 전역 변수
    snippetsDir = file('build/generated-snippets')
}

test {
    // https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/
    outputs.dir snippetsDir
}

asciidoctor {
    // ./gradlew asciidoctor
    inputs.dir snippetsDir
    configurations 'asciidoctorExt'
    sources {
        // 특정 파일만 html로 만든다.
        include("**/index.adoc")
    }
    // 다른 adoc 파일을 include 할 때 경로를 baseDir로 맞춘다.
    baseDirFollowsSourceFile()
    dependsOn test
}

bootJar {
    // mkdir -p src/docs/asciidoc
    // 위 디렉토리에 index.adoc 같은 메인 문서는 수동으로 작성 필요.
    // ./gradlew :2-spring:clean :2-spring:bootJar -i
    dependsOn asciidoctor
    println("${asciidoctor.outputDir}")
    from("${asciidoctor.outputDir}") {
        // 실행 후 localhost:8080/docs/index.html 로 확인할 수 있음.
        // 혹은 이 설정을 빼고 앱 배포 후 문서 전용 서버로 배포.
        into "static/docs"
    }
}
